//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmManagement.Persistence.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string TitleName { get; set; }
        public string ReleaseYear { get; set; }
        public string Director { get; set; }
        public string PlayTime { get; set; }
        public string Rating { get; set; }
        public Nullable<int> GenreId { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
